# Generated by Django 5.2.15 on 2026-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('enrollment_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('address', models.TextField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
    ]
